## Testing notebook for my ai lib

In [1]:
from lou.NL import *

In [2]:
def sigmoid(x):
    return 1/(1+np.exp(-x))
def dsigmoid(x):
    s = sigmoid(x)
    return s*(1-s)

Network = General_Network(struct=[9,10,1], f=sigmoid, df=dsigmoid)



In [3]:
for w in Network.Weights:
    print(w.shape)

for b in Network.Biases:
    print(b.shape)

(10, 9)
(1, 10)
(10, 1)
(1, 1)


In [4]:
Network.frontprop(np.array([[1,0,0,0,0,0,0,0,0]]))

[(None,
  array([[1],
         [0],
         [0],
         [0],
         [0],
         [0],
         [0],
         [0],
         [0]])),
 (array([[0.70317242],
         [0.94395399],
         [0.54093133],
         [0.79352023],
         [0.76588244],
         [0.89461463],
         [0.76681513],
         [0.77347037],
         [1.35647562],
         [1.30555944]]),
  array([[0.66889076],
         [0.71989765],
         [0.63202904],
         [0.68858669],
         [0.68262951],
         [0.70984155],
         [0.68283154],
         [0.68427113],
         [0.7951863 ],
         [0.78676914]])),
 (array([[5.52986946]]), array([[0.99604916]]))]

In [5]:
#this data only works for a network with the same configuration as seen above.

data = [(np.array([0,0,0,0,0,0,0,0,0]), np.array([0])), 
        (np.array([1,0,0,0,0,0,0,0,0]), np.array([0])), 
        (np.array([0,1,0,0,0,0,0,0,0]), np.array([0])), 
        (np.array([0,0,1,0,0,0,0,0,0]), np.array([0])), 
        (np.array([0,0,0,1,0,0,0,0,0]), np.array([0])),
        (np.array([0,0,0,0,1,0,0,0,0]), np.array([0])),
        (np.array([0,0,0,0,0,1,0,0,0]), np.array([1])),
        (np.array([0,0,0,0,0,0,1,0,0]), np.array([1])),
        (np.array([0,0,0,0,0,0,0,1,0]), np.array([1])),
        (np.array([0,0,0,0,0,0,0,0,1]), np.array([1])),
        (np.array([1,0,1,0,0,0,0,0,0]), np.array([0])),
        (np.array([1,1,0,0,0,0,0,0,0]), np.array([0])),
        (np.array([0,0,0,0,0,1,0,0,1]), np.array([1])),
        (np.array([1,0,0,0,0,0,0,0,1]), np.array([1])),
        (np.array([1,0,1,0,0,0,1,0,1]), np.array([1])),
        (np.array([0,0,1,1,0,0,0,0,1]), np.array([1])),
        (np.array([1,0,0,0,0,0,0,1,1]), np.array([1]))]


In [6]:
print(Network.meancost(data))
Network.train(data=data, tries=10000, verbose=1000)
Network.meancost(data)

0.23326191587318404
Loop number 0
Loop number 1000
Loop number 2000
Loop number 3000
Loop number 4000
Loop number 5000
Loop number 6000
Loop number 7000
Loop number 8000
Loop number 9000


np.float64(0.0009820512572893513)

In [7]:
# test with a new configuration mainting a start of 9 and an end of 1
Network2 = NeuralNetwork([9,5,5,1])

print(Network2.meancost(data))

Network2.train(data, tries=10000)

print(Network2.meancost(data))

0.21400633038590308
0.014820762405335404


In [8]:
Network2.export('./network3')
Network3 = ImportNetwork("./network3")
assert(Network3.meancost(data)==Network2.meancost(data))
    

Export succesful


In [9]:
from lou.Tokenizer import CharTokenizer

print(Network.FeedTokens(CharTokenizer, "HelloNeighbout"))

[[0.9814755062365461], [0.0009732804425122547]]
